#!/usr/bin/env python3

import sys
from analyzer import Analyzer
import helpers
from termcolor import colored

if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")

tweets = helpers.get_user_timeline(sys.argv[1], 50)

analyzer = Analyzer()

try:
    for tweet in tweets:
        
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print (colored(score, "green"), colored(tweet, "green"))
        elif score < 0.0:
            print (colored(score, "red"), colored(tweet, "red"))
        else:
            print (colored(score, "yellow"), colored(tweet, "yellow"))

except TypeError:
    sys.exit("Error")